Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2019-11, with the labels that each got.

#251 Make system tests more stable
  run_tests.py
  tests/gem_jaws_manager.py
  tests/instron_stress_rig.py
  tests/ips.py
  tests/polaris_jaws_manager.py
  tests/refl.py
Labels: size/S

#249 Ticket 4720 - Jasco: pump for volume doesn't work correctly
  tests/jsco4180.py
Labels: size/S

#257 Switch assertion orders, fix wm323 test names
  tests/instron_stress_rig.py
  tests/keithley_2700.py
  tests/wm323.py
Labels: size/S

#256 Ticket 4899 - Reflectometry: Fix error when DisplcementDriver is created based on a component which is out of the beam
  test_config/refl_init/refl/config.py
  test_config/refl_init/refl/params.txt
Labels: size/XS

#246 Ticket651 add ioc cryosms
  tests/cryosms.py
Labels: size/M

#259 Ignore messages about the log client not being able to connect
  utils/testing.py
Labels: size/S

#248 Ticket 4588 - Monitor Stall
  tests/refl.py
Labels: size/S

#254 Ticket4131 zero motors
  test_config/good_for_refl/refl/config.py
  tests/refl.py
  utils/channel_access.py
Labels: size/L

#260 LINMOT: Fix failing tests
  tests/linmot.py
Labels: size/S

#261 Fix various tests
  tests/inhibitr.py
  tests/polaris_jaws_manager.py
  tests/simple.py
  utils/testing.py
Labels: size/M

#262 Be more defensive about checking that necessary PVs exist
  tests/simple.py
Labels: size/XS
