Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2019-10, with the labels that each got.

#244 Fix the tests
  tests/jaws.py
  tests/jaws_split.py
Labels: size/M

#245 Add decorator to some unstable tests.
  common_tests/fermichopper.py
  tests/ccd100.py
  tests/instron_stress_rig.py
  tests/jaws_manager.py
  tests/lksh218.py
  tests/rknps.py
  tests/superlogics.py
  utils/testing.py
Labels: size/M

#250 Skip unstable tests
  tests/attocube.py
  tests/nimrod_jaws_manager.py
Labels: size/XS

#253 Update README.md
  README.md
Labels: size/XS

#252 Added tests to check that the correct records are in alarm when device is disconnected
  tests/eurotherm.py
Labels: size/S
