Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2019-12, with the labels that each got.

#258 Add tests for alarms at reflectometry parameter level
  test_config/good_for_refl/refl/mode.txt
  tests/refl.py
Labels: size/M

#268 Mark unstable tests as unstable
  tests/simple.py
Labels: size/XS

#266 Ticket3876 muon ice fridge
  tests/icefrdge.py
  utils/emulator_launcher.py
Labels: size/L

#263 Ticket4872 jasco bug
  tests/jsco4180.py
Labels: size/M

#270 Add test that reads/writes a PV 1000 times
  tests/simple.py
  utils/channel_access.py
Labels: size/XS

#271 Add annotations and further notes to some motion tests
  tests/attocube.py
  tests/nimrod_jaws_manager.py
Labels: size/M

#273 Test references added to comments
  tests/attocube.py
Labels: size/XS

#272 Add unstable test decorator to further tests
  tests/simple.py
Labels: size/XS

#264 Ticket4838 zero field strength
  tests/zfmagfld.py
Labels: size/L

#267 Ticket4855 muon zero field controller
  tests/zfcntrl.py
Labels: size/XL

#269 made tests run on ioc one not two
  tests/icefrdge.py
Labels: size/XS

#275 Attempt to fix tests
  tests/jsco4180.py
  utils/channel_access.py
Labels: size/S
