Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-07, with the labels that each got.

#342 Add test
  tests/jsco4180.py
Labels: size/S

#340 Add macros
  tests/superlogics.py
Labels: size/S

#325 Ticket5365
  tests/mecfrf.py
Labels: size/M

#346 increase timeout for jasco
  tests/jsco4180.py
Labels: size/XS

#349 Fix jaws axis definitions
  tests/jaws_split.py
Labels: size/XS

#339 Ticket 5412: Add Danfysik test that restarts IOC
  common_tests/danfysik.py
  run_tests.py
  tests/danfysik8000.py
  tests/danfysik8500.py
  tests/danfysik8800.py
  tests/simple.py
  utils/ioc_launcher.py
Labels: size/L

#351 Use ProcServLauncher
  tests/danfysik_calibrated.py
Labels: size/XS

#347 Add tests to check error status set correctly
  tests/sans2d_vacuum.py
Labels: size/S

#341 test axis driver selection
  test_config/good_for_refl/refl/config.py
  tests/refl.py
Labels: size/S

#353 Skip on RKNPS
  common_tests/danfysik.py
Labels: size/XS

#354 Fix mecfrf test
  tests/mecfrf.py
  utils/channel_access.py
Labels: size/M

#348 Ticket5333 helium recovery fins plc
  tests/helium_recovery_plc.py
  utils/channel_access.py
Labels: size/L
