Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-02, with the labels that each got.

#290 Suppress overload alarms in manual mode
  tests/zfcntrl.py
Labels: size/M

#291 Implement tests for lakeshore 372
  tests/lakeshore372.py
Labels: size/L

#295 Fix lakeshore ioc tests
  tests/lakeshore460.py
Labels: size/XS

#255 Ticket4831 cryosms simple start
  tests/cryosms.py
Labels: size/M

#296 Fix excessive logging
  tests/ccd100.py
Labels: size/XS

#298 Install debug build if debug system job
  Jenkinsfile
Labels: size/XS
