Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-10, with the labels that each got.

#373 Ticket5780 fix tests
  common_tests/danfysik.py
  tests/danfysik_calibrated.py
  tests/danfysik_common_calib.py
  tests/jaws.py
Labels: size/M

#374 Ticket 5342: Skipped tests that do not reflect device behaviour
  tests/rotsc.py
Labels: size/M

#377 Add tests for user buttons and variables
  tests/instetc.py
  utils/testing.py
Labels: size/M

#371 Ticket5546 little blue cryostat
  tests/mercuryitc.py
Labels: size/L

#367 Ticket 5356 - Tests check for non existant PV's
  tests/dma4500m.py
  tests/gamry.py
  tests/linmot.py
  tests/motion_setpoints.py
  tests/moxa1210.py
  tests/moxa1240.py
  tests/moxa1262.py
  tests/readascii.py
  tests/rikenportchangeover.py
  tests/rikenrb2modechangeover.py
  tests/sm300.py
Labels: size/S

#375 Ticket5720
  tests/samplechanger.py
Labels: size/M

#379 Ticket5725 samplechanger reload configs
  tests/samplechanger.py
Labels: size/L

#372 Add tests for taking measurements and writing data to PV.
  tests/lsicorr.py
  tests/refl_init.py
  utils/ioc_launcher.py
Labels: size/M

#381 Set path to cryostat config
  tests/mercuryitc.py
Labels: size/XS
