Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-04, with the labels that each got.

#313 Ticket4309 refl multiple parked positions
  test_config/good_for_refl/refl/config.py
  test_config/refl_init/refl/config.py
  tests/refl.py
Labels: size/M

#297 Added option for which PLC to log in to
  utils/emulator_launcher.py
Labels: size/XS

#316 Wait for new value to hold before continuing
  tests/lsicorr.py
Labels: size/XS

#317 Ticket 5266: Reconnect DAQmx on error
  tests/DAQmx.py
  utils/emulator_launcher.py
Labels: size/M

#315 Keithley tests modified to work with emulator additions
  tests/keithley_2700.py
Labels: size/S

#321 Tidied up and expanded lakeshore tests
  tests/lakeshore460.py
Labels: size/L

#314 add tests for axis in position calculation
  tests/axis.py
Labels: size/M

#306 Ticket 4287: update from tests
  tests/rotsc.py
  utils/channel_access.py
  utils/emulator_launcher.py
Labels: size/L

#300 Add tests for DMA4500M
  tests/dma4500m.py
Labels: size/L

#320 Adjust tests from hardware
  tests/mezflipr.py
Labels: size/XS

#312 Add new argument to just run recsim or devsim
  README.md
  run_tests.py
Labels: size/S

#308 Ticket4935 correlator saving data
  tests/lsicorr.py
Labels: size/XS
