Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-11, with the labels that each got.

#376 Ticket3185 remote mode reliability
  common_tests/kepco.py
  tests/kepco_no_rem.py
  tests/kepco_rem.py
  utils/channel_access.py
  utils/ioc_launcher.py
Labels: size/L

#360 Ticket 4573: SANS2D named aperture and guide positions
  tests/motion_setpoints.py
Labels: size/XL

#380 Ticket 5661: Added tests for ramping KEPCO
  common_tests/kepco.py
Labels: size/M

#385 Correct motionsetpoints.cmd syntax
  test_support/loq_aperture/motionsetpoints.cmd
  tests/motion_setpoints.py
Labels: size/S

#384 Ticket5663: HTS Smart Monitor
  tests/smrtmon.py
Labels: size/M

#319 Ticket5259 switch rates mid ramp
  tests/cryosms.py
Labels: size/M

#350 Ticket4581 front detector beam stop
  tests/sans2d_vacuum_tank.py
  utils/axis.py
Labels: size/M

#387 Fix system tests iocs
  common_tests/DAQmx.py
  tests/DAQmx.py
  tests/DAQmx_monster.py
  tests/cryosms.py
  tests/danfysikdisableautoonoff.py
  tests/mercuryitc.py
  utils/ioc_launcher.py
Labels: size/M

#388 Fix system test io cs
  common_tests/kepco.py
  tests/kepco_no_rem.py
  tests/kepco_rem.py
Labels: size/S

#382 Ticket5494
  tests/tizr.py
Labels: size/L

#383 Ticket 5662: Added tests for Kepco magnet calibration
  common_tests/kepco.py
  tests/eurotherm.py
  utils/calibration_utils.py
Labels: size/L

#378 Ticket5296 danfysik polarity
  common_tests/danfysik.py
  tests/danfysik8000.py
  tests/danfysik8500.py
  tests/danfysik8800.py
  tests/danfysik_unipolar.py
Labels: size/M

#390 Set correct PV into alarm
  tests/zfcntrl.py
Labels: size/XS
