Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-12, with the labels that each got.

#391 Fix system tests iocs
  tests/eurotherm.py
Labels: size/S

#386 Ticket 5866: Updated to use python 3 for Lewis
  utils/emulator_launcher.py
Labels: size/XS

#389 Fixed and added couple ioc tests
  tests/smrtmon.py
Labels: size/S

#392 Add test
  tests/ilm200.py
Labels: size/M

#395 Ticket4890 convert to Python 3
  common_tests/moxa12XX.py
  run_all_tests.bat
  run_tests.py
  tests/dma4500m.py
  tests/helium_recovery_plc.py
  tests/ilm200.py
  tests/jaws.py
  tests/keithley2400.py
  tests/keithley_2001.py
  tests/lakeshore340.py
  tests/lakeshore372.py
  tests/loq_aperture.py
  tests/mecfrf.py
  tests/moxa1210.py
  tests/moxa1240.py
  tests/moxa1262.py
  tests/readascii.py
  tests/samplechanger.py
  tests/sans2d_vacuum_collision_avoidance.py
  tests/separator.py
  tests/tdk_lambda_genesys.py
  tests/triton.py
  tests/zfcntrl.py
  utils/emulator_launcher.py
  utils/ioc_launcher.py
Labels: size/M

#394 Add same lock and cleanup code as in system tests
  Jenkinsfile
Labels: size/M

#398 Fix lewis backdoor
  utils/emulator_launcher.py
Labels: size/S

#393 Ticket5095 pt2025 support ioc test
  tests/pt2025.py
Labels: size/M

#399 change_of_field
  tests/pt2025.py
Labels: size/XS

#400 Ticket5978 - remove imp in favour of importlib
  run_utils.py
Labels: size/XS

#401 Remove EPICS dir at end
  Jenkinsfile
Labels: size/XS

#402 Improve clean up
  Jenkinsfile
Labels: size/S

#404 Move junction removal to when lock is held
  Jenkinsfile
Labels: size/XS
