Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-06, with the labels that each got.

#326 Ticket5338 add ioc flipprps
  .gitignore
  tests/flipprps.py
Labels: size/M

#323 Add initial gamry test
  tests/gamry.py
  utils/emulator_launcher.py
Labels: size/M

#336 Fix ioc tests
  tests/danfysik_local_calib.py
  utils/emulator_launcher.py
Labels: size/XS

#338 Add tests
  tests/sans2d_vacuum.py
Labels: size/M

#334 Ticket4884 refl to py3
  tests/refl.py
  tests/refl_init.py
Labels: size/XS

#335 Ticket1392 mercury epics ioc
  tests/mercury.py
  tests/mercuryitc.py
  utils/testing.py
Labels: size/L

#337 Ticket5432 bench component and parameters
  test_config/good_for_refl/refl/config.py
  test_config/refl_init/refl/config.py
  tests/refl.py
  tests/refl_init.py
Labels: size/L
