Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-01, with the labels that each got.

#274 Re-enable tests post 64bit pointer fix in attocube code
  tests/attocube.py
Labels: size/XS

#280 Revert "Re-enable tests post 64bit pointer fix in attocube code"
  tests/attocube.py
Labels: size/XS

#281 removed blank line
  tests/kepco.py
Labels: size/XS

#279 Ticket5043
  tests/check_stability.py
  tests/tdk_lambda_genesys.py
  utils/emulator_launcher.py
Labels: size/L

#278 Ticket3850 daq disconnect
  tests/zfcntrl.py
  tests/zfmagfld.py
Labels: size/M

#282 Ticket4926 comission ice fridge
  tests/icefrdge.py
Labels: size/S

#285 Fix sp2xx tests
  tests/sp2xx.py
Labels: size/S

#286 Tests for danfysik calibrated with scale factors
  tests/danfysik_calibrated.py
Labels: size/M

#288 Fix system tests
  common_tests/danfysik.py
  tests/ccd100.py
  utils/testing.py
Labels: size/M

#276 Make tp flag fail better
  run_tests.py
Labels: size/XS

#287 Add test for setting kepco to remote mode
  tests/kepco.py
Labels: size/S

#289 Add test
  tests/itc503.py
Labels: size/S
