Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-05, with the labels that each got.

#322 Ticket4289 config for crisp
  test_config/good_for_refl/refl/config.py
Labels: size/L

#327 Report IOC startup failures
  run_tests.py
Labels: size/M

#329 Fix Reflectometry redefine slit tests
  test_config/good_for_refl/refl/config.py
Labels: size/XS

#328 Create specific named function for failed test
  run_tests.py
Labels: size/S

#331 Warn if no process killed
  utils/ioc_launcher.py
Labels: size/S

#330 Prefix logs with test name and archive artifacts
  Jenkinsfile
  run_all_tests.bat
  run_tests.py
  tests/DAQmx.py
  utils/emulator_launcher.py
  utils/ioc_launcher.py
  utils/log_file.py
Labels: size/M

#333 If install fails don't run tests
  Jenkinsfile
Labels: size/XS

#318 Added test for disabling Danfysik PSU auto on/off and added compatibility with…
  tests/danfysik8000.py
  tests/danfysik8500.py
  tests/danfysik8800.py
  tests/danfysik_calibrated.py
  tests/danfysik_common_calib.py
  tests/danfysik_local_calib.py
  tests/danfysikdisableautoonoff.py
Labels: size/M

#332 Ticket 4555: SANS2D vacuum system
  tests/fins.py
  tests/larmor_bench_fins.py
  tests/sans2d_vacuum.py
  utils/channel_access.py
Labels: size/L
