Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2020-03, with the labels that each got.

#292 added test for voltage limits
  tests/zfcntrl.py
Labels: size/M

#293 Ticket5057 cryosms basic qsm
  tests/cryosms.py
Labels: size/M

#277 Test refl value parameters
  test_config/good_for_refl/refl/config.py
  tests/refl.py
Labels: size/S

#299 Implement tests
  tests/mezflipr.py
Labels: size/L

#301 Ignore messages from autosave
  utils/testing.py
Labels: size/S

#302 Add super mirror to test and run polarised test
  test_config/good_for_refl/refl/config.py
  tests/refl.py
Labels: size/M

#304 Fix rotsc test
  tests/rotsc.py
  utils/channel_access.py
Labels: size/M

#303 Fix PV names
  tests/refl.py
  tests/refl_init.py
Labels: size/XS

#309 Fix ioc system tests refl
  test_config/good_for_refl/refl/config.py
  tests/refl.py
Labels: size/XS

#305 Use environment variable if present
  tests/danfysik_local_calib.py
Labels: size/XS

#307 Add microsoft teams connector
  Jenkinsfile
  Jenkinsfile7
Labels: size/M

#294 Ticket4918 sans dls
  tests/lsicorr.py
  utils/channel_access.py
  utils/ioc_launcher.py
Labels: size/L

#310 Ticket 4488: Removed attocube as not used
  tests/attocube.py
Labels: size/M

#311 Update tests for AT_SETPOINT PV
  tests/zfcntrl.py
Labels: size/M
