Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2021-01, with the labels that each got.

#405 Telnetlib calls must use bytes
  tests/kepco_no_rem.py
  utils/ioc_launcher.py
Labels: size/M

#406 Fix tests
  common_tests/danfysik.py
  common_tests/fermichopper.py
  utils/emulator_launcher.py
Labels: size/S

#397 Ticket4915 add tests
  run_tests.py
  test_data/CAENv895/vmeconfig_ioctestdefaults.cfg
  tests/CAENv895.py
Labels: size/L

#403 Basic test for IOC startup
  tests/fmr.py
Labels: size/M

#409 Fix some tests broken in python 3
  tests/flipprps.py
  tests/icefrdge.py
  tests/ips.py
  tests/kepco_no_rem.py
  tests/kepco_rem.py
  tests/linmot.py
  tests/rkndio.py
  utils/emulator_launcher.py
Labels: size/M

#408 Ticket5099 musr thurlby
  common_tests/tti_common.py
  tests/tti355.py
  tests/ttiex355p.py
Labels: size/L

#410 Fix ZMQ issue?
  utils/emulator_launcher.py
Labels: size/XS

#396 Ticket 5896: Added tests for the refl long axis
  test_config/good_for_refl/refl/config.py
  tests/refl.py
Labels: size/S
