Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2021-06, with the labels that each got.

#463 add sleep for zfcntrl autosave test - not getting saved quickly enough
  tests/zfcntrl.py
Labels: size/XS

#464 Sped up refl tests
  tests/refl.py
Labels: size/M

#456 Remove python 2 reference
  run_tests.py
  tests/mezflipr_v1.py
  utils/emulator_launcher.py
  utils/ioc_launcher.py
Labels: size/S

#462 Ticket 5739: Add tests for the mclennan
  tests/mclennan.py
Labels: size/M

#466 fix pythondir - use python3dir
  run_tests.py
Labels: size/XS

#465 add test for trigger
  tests/tekafg3XXX.py
Labels: size/XS

#468 fix zfcntrl autofeedback autosave test and speedup
  tests/zfcntrl.py
Labels: size/XS

#469 speed up tizr tests
  tests/tizr.py
Labels: size/S

#470 Speed up hlx tests
  common_tests/fermichopper.py
  tests/aldn1000.py
  tests/eurotherm.py
  tests/hlx503.py
Labels: size/M

#471 speed up itc503 tests - use default_wait_time=0.0
  tests/itc503.py
Labels: size/XS

#474 speeding up tests, fixing one broken by COMP:D
  tests/jsco4180.py
Labels: size/S
