Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2021-05, with the labels that each got.

#451 adding sleep in readascii test as it wasn't ramping quickly enough
  tests/readascii.py
Labels: size/XS

#454 Ticket 6414: Added test for setting coords directly in motion set points
  tests/motion_setpoints.py
Labels: size/XS

#453 Ticket 6423: Added test for motion set points restarting
  tests/linmot.py
Labels: size/S

#455 adding ioc test for autofeedback mode autosaving
  tests/kepco_no_rem.py
  tests/zfcntrl.py
  utils/ioc_launcher.py
Labels: size/M

#458 fix the tests broken by the reverted lewis backdoor control
  common_tests/fermichopper.py
  common_tests/kepco.py
  tests/flipprps.py
  tests/ips.py
  tests/keithley_2001.py
  tests/kepco_no_rem.py
  tests/kepco_rem.py
  tests/knr1050.py
  tests/linmot.py
  tests/rkndio.py
  utils/emulator_launcher.py
Labels: size/M

#449 ttiex355p: Test bug fixes
  tests/ttiex355p.py
Labels: size/M

#460 fix more tests after lewis backdoor control change
  common_tests/danfysik.py
  tests/rotsc.py
  tests/sm300.py
Labels: size/S

#461 Fix macro value type for refl_init tests
  tests/refl_init.py
Labels: size/XS
