Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2021-11, with the labels that each got.

#494 Rename waveguide instance from comment with guides
  tests/sans2d_apertures_guides.py
Labels: size/XS

#515 Make sure we're not setting MRES then trying to move
  tests/oscillating_collimator_let.py
  tests/refl.py
Labels: size/XS

#516 Revert "Make sure we're not setting MRES then trying to move"
  tests/oscillating_collimator_let.py
  tests/refl.py
Labels: size/XS

#491 Remove older CA tests and add new tests
  tests/sans2d_vacuum_collision_avoidance.py
  tests/sans2d_vacuum_tank.py
Labels: size/L

#518 fix sans2d test failure error message
  tests/sans2d_vacuum_collision_avoidance.py
Labels: size/XS

#519 sans2d fix test
  tests/sans2d_vacuum_tank.py
Labels: size/M
