Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2021-02, with the labels that each got.

#407 Lakeshore 340: Add tests for setting and readback of excitation values
  tests/lakeshore340.py
  utils/channel_access.py
Labels: size/L

#411 Ticket 6151: Added tests for setting negative currents
  common_tests/kepco.py
  tests/kepco_no_rem.py
  tests/kepco_rem.py
Labels: size/S

#412 Kepco: Test to check current:sp count only changes by one when set
  common_tests/kepco.py
  tests/kepco_rem.py
Labels: size/S

#414 Fix keithley 2001 tests
  tests/keithley_2001.py
Labels: size/S

#415 Fix knr1050 tests and speed them up
  tests/knr1050.py
  utils/channel_access.py
Labels: size/M

#416 Fix lakeshore460 tests
  tests/lakeshore460.py
Labels: size/XS

#413 Ticket653 add ioc hifimags
  tests/hifimags.py
Labels: size/L

#418 removing linmot test - hangs on jenkins
  tests/linmot.py
Labels: size/L

#419 Use inbuilt asserts to speed up tests
  tests/keithley_2001.py
Labels: size/S

#421 adding test for smoothing
  tests/zfmagfld.py
Labels: size/M

#422 Stopped fermi_chopper running in recsim
  tests/fzj_dd_fermi_chopper.py
Labels: size/M

#426 adding linmot tests back in
  tests/linmot.py
  utils/emulator_launcher.py
Labels: size/L

#425 Run the v1 mezei flipper emulator in python 2
  tests/mezflipr_v1.py
  utils/emulator_launcher.py
Labels: size/S
