Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2021-03, with the labels that each got.

#427 Ticket6256
  utils/emulator_launcher.py
Labels: size/XS

#424 Fixed MOXA1210 tests
  tests/moxa1210.py
Labels: size/XS

#417 Tests for the comms for the ITC503/Heliox Refrigerator
  README.md
  run_tests.py
  tests/hlx503.py
  utils/emulator_launcher.py
Labels: size/L

#420 Add tests for egu
  tests/refl.py
  tests/refl_init.py
Labels: size/S

#428 Fix run of tests getting emulator data
  run_tests.py
Labels: size/XS

#430 Add galil encoder test
  tests/galil.py
Labels: size/M

#432 Revert "Ticket6256 " - add logging back in for the linmot tests
  utils/emulator_launcher.py
Labels: size/XS

#433 Fix tests now getting all commands back as a list from lewis
  tests/rotsc.py
  tests/sm300.py
Labels: size/S

#435 Fix Keithley 2700: Speed up tests and clear buffer as final thing in set up
  tests/keithley_2700.py
Labels: size/S

#429 Ticket5990 slew rate
  tests/danfysik8500.py
Labels: size/S

#436 adding prints in as well as logs to file
  utils/emulator_launcher.py
Labels: size/XS

#441 Configure poll rate for tests
  tests/triton.py
Labels: size/XS

#440 Adjust test for new averaging method
  tests/zfmagfld.py
Labels: size/S

#437 Ticket6202 add ioc afg3021 b
  tests/tekafg3XXX.py
Labels: size/M

#439 removing ioc test for icefrdge
  tests/icefrdge.py
Labels: size/L

#431 Rework hlx503 refrigerator communications
  tests/hlx503.py
Labels: size/L
