Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2021-08, with the labels that each got.

#475 Added tests for Danfysik9100
  tests/danfysik9X00.py
Labels: size/M

#477 Fix refl system tests
  tests/refl.py
Labels: size/XS

#478 Add notes on how to see all output
  Makefile
  README.md
Labels: size/S

#479 removing rknps ioc tests
  common_tests/danfysik.py
  tests/rikenportchangeover.py
  tests/rikenrb2modechangeover.py
  tests/rknps.py
Labels: size/L

#483 Refl init velocities
  tests/refl.py
Labels: size/XS
