Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2022-11, with the labels that each got.

#570 Ticket7400
  common_tests/kepco.py
Labels: size/S

#543 fixing wish orc tests - removing redundant radius etc. sets as they a…
  tests/oscillating_collimator_wish.py
Labels: size/M

#573 Increase timeout
  common_tests/eurotherm.py
Labels: size/XS

#571 Ticket7070
  tests/refl.py
Labels: size/M

#574 Ticket7073
  tests/refl.py
Labels: size/S

#576 Ticket7484
  common_tests/eurotherm.py
Labels: size/S

#547 Add check for centre not moving if blade moves
  test_config/good_for_refl/jaws.cmd
  tests/jaws.py
Labels: size/M
