Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2022-08, with the labels that each got.

#551 Only read from proc.stdout once
  utils/emulator_launcher.py
Labels: size/XS

#549 Ticket6425 add file checks
  tests/motion_setpoints.py
Labels: size/XS

#553 Add Percent of Volt Limit Tests
  tests/mercuryitc.py
Labels: size/M

#554 Add TTIPLP Overcurrent and Overvolt trip tests
  tests/ttiplp.py
Labels: size/M

#443 Ticket5993 setup correctly
  tests/cryosms.py
Labels: size/L

#555 Added BGRSCRPT IOC test.
  tests/bgrscrpt.py
Labels: size/M

#559 Fix RAMP_FILE path for non standard installations
  tests/cryosms.py
Labels: size/XS

#560 Fix path join - need escaping or use /
  tests/cryosms.py
Labels: size/XS

#557 Ticket7276 constrain log size
  test_config/good_for_refl/refl/config_trunc.py
  tests/refl_trunc.py
Labels: size/L

#552 Ticket7261
  tests/lksh336.py
Labels: size/M
