Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2022-09, with the labels that each got.

#561 Rework test to cover SP behaviour
  tests/tpg300.py
Labels: size/XS

#558 Refactor IOC test framework device disconnection tests & add README documentation
  README.md
  common_tests/danfysik.py
  common_tests/kepco.py
  tests/ag33220a.py
  tests/amint2l.py
  tests/chtobisr.py
  tests/cybaman.py
  tests/dma4500m.py
  tests/edwardstic.py
  tests/eurotherm.py
  tests/flipprps.py
  tests/fzj_dd_fermi_chopper.py
  tests/heliox.py
  tests/jsco4180.py
  tests/keylkg.py
  tests/knr1050.py
  tests/lakeshore372.py
  tests/lksh218.py
  tests/mecfrf.py
  tests/mercuryitc.py
  tests/mezflipr_v2.py
  tests/smrtmon.py
  tests/superlogics.py
  utils/emulator_launcher.py
Labels: size/L

#562 Add tests for INSTRONA
  common_tests/instron_base.py
  tests/instron_stress_rig.py
  tests/instron_stress_rig_arby.py
Labels: size/XXL

#564 Explicitly specify unbuffered
  README.md
  run_all_tests.bat
  utils/emulator_launcher.py
Labels: size/S

#565 Test Tektronix afg3xxx When SCAN Macro in Passive Mode
  tests/tekafg3XXX.py
Labels: size/M

#563 Add Tests for VTI Software Pressure Control Functionality
  tests/mercuryitc.py
  tests/mercuryitc_FLOW_SPC.py
  tests/mercuryitc_VTI_SPC.py
Labels: size/XL

#566 Ticket7376
  tests/keylkg.py
Labels: size/S
