Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2022-12, with the labels that each got.

#580 Ticket7241 riken plc configuration
  tests/rikenfe_plc.py
  utils/channel_access.py
Labels: size/L

#575 Ticket #7385: Add arch. skip mechanism
  README.md
  run_tests.py
  run_utils.py
  tests/astrium.py
  tests/fermichopper_maps.py
  tests/fermichopper_merlin.py
  tests/instron_stress_rig.py
  tests/keithley_2001.py
  tests/mk3chopper.py
  tests/sans2d_vacuum.py
  utils/build_architectures.py
Labels: size/L

#579 Ticket5872 Tests for Danfysik and RIKENFE PLC for RIKEN OPI
  common_tests/danfysik.py
  tests/rikenfe_plc.py
Labels: size/M

#583 Fix build arch for all directories
  run_tests.py
Labels: size/S

#578 make NOSIM launch nothing for TC ioc
  utils/emulator_launcher.py
Labels: size/XS
