Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2023-08, with the labels that each got.

#605 Fix refl tests
  test_config/good_for_refl/refl/config.py
  tests/refl.py
Labels: size/XS

#606 Add kepco range
  common_tests/kepco.py
Labels: size/M

#593 Ticket6777
  common_tests/eurotherm.py
  tests/eurotherm_eibisynch.py
  tests/eurotherm_modbus.py
  tests/eurotherm_modbus_needlevalve.py
Labels: size/L

#607 Adding tests for the 1242
  tests/moxa1242.py
Labels: size/L
