Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2023-01, with the labels that each got.

#585 Ticket7530
  tests/bgrscrpt.py
  tests/fermi_chopper_lifter.py
  tests/fmr.py
  tests/inhibitr.py
  tests/mclennan.py
  tests/sans2d_vacuum.py
  utils/ioc_launcher.py
Labels: size/S

#581 Ticket7058
  tests/superlogics.py
Labels: size/L

#577 Instron
  common_tests/instron_base.py
  tests/instron_stress_rig.py
  tests/instron_stress_rig_arby.py
Labels: size/M

#587 scale min time lag before applying to numpy array
  tests/lsicorr.py
Labels: size/XS

#582 Added RIKENFE pumpset summary tests
  tests/rikenfe_plc.py
Labels: size/M

#586 Rikenfe rb2 protocol
  tests/danfysikRIKEN.py
Labels: size/M
