Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2024-12, with the labels that each got.

#649 Set disable_pcon
  utils/ioc_launcher.py
Labels: size/XS

#643 Ticket8359 create p4p wrapper
  README.md
  global_settings.py
  requirements.txt
  run_tests.py
  run_utils.py
  tests/galil.py
  utils/__init__.py
  utils/build_architectures.py
  utils/channel_access.py
  utils/device_launcher.py
  utils/emulator_launcher.py
Labels: size/L

#650 Fix incorrect type narrowing
  utils/channel_access.py
Labels: size/XS

#647 Improve test coverage
  tests/muontpar.py
Labels: size/M

#651 start instetc before main ioc
  tests/muontpar.py
Labels: size/S
