Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2024-04, with the labels that each got.

#619 Ticket_8284_Allow_certain_values_to_be_editable_without_restarting_IOC
  tests/mclennan.py
Labels: size/M

#620 Ensure subprocess termination on python exit
  run_tests.py
Labels: size/XS

#621 Allow for exiting tests before tests to handle cleanup of ioc
  run_tests.py
  utils/emulator_launcher.py
  utils/ioc_launcher.py
Labels: size/L
