Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2024-10, with the labels that each got.

#642 Add tests for AFG arbitrary commands
  tests/tekafg3XXX.py
Labels: size/XS

#644 fix hifimags tests to reflect scientist requirements
  tests/hifimags.py
Labels: size/L

#645 Ruff/pyright
  utils/axis.py
  utils/build_architectures.py
  utils/calibration_utils.py
  utils/device_launcher.py
  utils/emulator_exceptions.py
  utils/emulator_launcher.py
  utils/formatters.py
  utils/free_ports.py
  utils/ioc_launcher.py
  utils/log_file.py
  utils/testing.py
Labels: size/XL

#646 Fix unstable test deco
  utils/testing.py
Labels: size/XS
