Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2024-06, with the labels that each got.

#631 Ticket8341_set_alarm_severity_based_on_macro
  common_tests/tpgx00.py
  tests/tpg300.py
Labels: size/L

#633 Fix test: use procServ launcher
  tests/tpg500.py
Labels: size/XS

#635 add tests for new scan macro
  tests/zfmagfld.py
Labels: size/M
