Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2024-05, with the labels that each got.

#624 add simple test to check ioc starts
  tests/tekdmm40X0.py
Labels: size/M

#622 Ticket8253_make_IOC_work_if_crate_is_power_cycled
  tests/mclennan.py
Labels: size/S

#623 Ticket8289 Add generic way to close emulator
  utils/emulator_launcher.py
  utils/tests/commandline_nested_test.bat
  utils/tests/commandline_test.bat
  utils/tests/test_emulator_launcher.py
Labels: size/M

#626 added missing EOL characters
  utils/tests/commandline_nested_test.bat
  utils/tests/commandline_test.bat
Labels: size/XS

#628 Ensure we only use psutil for non-lewis emulators
  utils/emulator_launcher.py
Labels: size/XS

#627 Print out log file locations for lewis and ioc
  utils/emulator_launcher.py
  utils/ioc_launcher.py
Labels: size/XS

#629 Remove usage of six
  common_tests/fermichopper.py
  common_tests/instron_base.py
  common_tests/jaws_manager_utils.py
  common_tests/moxa12XX.py
  common_tests/riken_changeover.py
  common_tests/tpgx6x.py
  common_tests/tti_common.py
  run_tests.py
  tests/edwardstic.py
  tests/zfcntrl.py
  utils/emulator_launcher.py
  utils/ioc_launcher.py
  utils/testing.py
Labels: size/M

#608 Set REMOTE_ON_SET to NO
  tests/kepco_no_rem.py
  tests/kepco_rem.py
  tests/zfcntrl.py
Labels: size/XS

#630 Ticket8357 multiple caen crates
  tests/CAENv895.py
Labels: size/S
