Repository ISISComputingGroup/EPICS-IOC_Test_Framework, pull requests merged in 2024-09, with the labels that each got.

#641 Delete old RB2 tests
  tests/danfysikRIKEN.py
Labels: size/M

#639 add test for muon tpar editor
  .gitignore
  test_data/muontpar/tpar.tpar
  tests/muontpar.py
Labels: size/M

#638 ramp symmetry test
  tests/tekafg3XXX.py
Labels: size/XS

#640 Fix tests
  tests/CAENv895.py
Labels: size/S
